### ISSUE TITLE
an open question: ChatGPT generated code may clone from another repository

### ISSUE THREAD

**Issue by Thompson-cyber** [genuinemerit/saskan#8]
**Description**: 
Hello, I apologize for bothering you as this might not be a real bug.  😊 I notice that the code used to create 3D plot in  [sphere_and_rect.py](https://github.com/genuinemerit/saskan-app/blob/9400d8f17d3cc3377e24e8d7e90a10e521776402/lab/math_lab/sphere_and_rect.py#L5)  was generated by ChatGPT. There is an open question about the code may clone from another repository with  GPL license. 
## Details

The  [sphere_and_rect.py](https://github.com/genuinemerit/saskan-app/blob/9400d8f17d3cc3377e24e8d7e90a10e521776402/lab/math_lab/sphere_and_rect.py#L5)    have been generated by ChatGPT with [```This code generated by ChatGPT. It is not exactly right,```](https://github.com/genuinemerit/saskan-app/blob/9400d8f17d3cc3377e24e8d7e90a10e521776402/lab/math_lab/sphere_and_rect.py#L5) comments.

However, the code from lines  32  to 39 seems to be a code clone with [draw.py](https://github.com/agarciamontoro/TFG/blob/2dc7c0b8bffaa3432f53c704fe749e48529f97e9/Software/Raytracer/Utils/draw.py#L67) file in  [agarciamontoro/TFG](https://github.com/agarciamontoro/TFG) repository. The main difference between the two code snippets is the parameters of ```ax.plot_surface```.  Additionally, the ChatGPT generated code was updated on **NOV/4/2023** and the cloned code was updated on **DEC/18/2016**.

**It's an open question because the plot function could be implemented in numerous ways.** But when [searched the code lines](https://github.com/search?q=u+%3D+np.linspace%280%2C+2+*+np.pi%2C+100%29+v+%3D+np.linspace%280%2C+np.pi%2C+100%29+%22x+%3D+r+*+np.outer%28np.cos%28u%29%2C+np.sin%28v%29%29%22+language%3APython&type=code) using GitHub search, the first search result is [agarciamontoro/TFG](https://github.com/agarciamontoro/TFG).

https://github.com/genuinemerit/saskan-app/blob/9400d8f17d3cc3377e24e8d7e90a10e521776402/lab/math_lab/sphere_and_rect.py#L32-L39

The  [sphere_and_rect.py](https://github.com/genuinemerit/saskan-app/blob/9400d8f17d3cc3377e24e8d7e90a10e521776402/lab/math_lab/sphere_and_rect.py#L5)  is under [MIT](https://github.com/genuinemerit/saskan-app?tab=MIT-1-ov-file#readme). However, the cloned code is under [GPL-2.0](https://github.com/agarciamontoro/TFG?tab=GPL-2.0-1-ov-file#readme) license.
According to the conditions of this GPL-2.0 license, there may be a potential license violation:

>```
>You may copy and distribute verbatim copies of the Program's
>source code as you receive it, in any medium, provided that you
>conspicuously and appropriately publish on each copy an appropriate
>copyright notice and disclaimer of warranty;
>```

1. How do you view potential license conflicts between ChatGPT-generated code and existing open-source code? This is still an open question because this function is simple and can be implemented in numerous ways.

2. Would you add some explanation about the open-source licenses of the ChatGPT generated code?

Thank you for your attention to this matter. I am sorry for any inconvenience caused.😊

**Comment by genuinemerit** [comment]
Thanks much for this note. I appreciate you bringing this to my attention. 
I have removed the code from my project alogether.
If I choose at a later time to include it as is, I will include with it an appropriate copyright notice. 

Speaking to your more general question, I believe I need to introduce a process into my development efforts where I not only test and review AI-generated code (which I find is often faulty), but also review it for licensing conflicts.
